[package]
name = "frames"
version = "0.1.0"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
petgraph = "0.4"
lazy_static = "1.2"
bytes = "0.4.12"
prost = "0.5"
prost-derive = "0.5"
